name: Buycraft
main: net.buycraft.Plugin
version: 6.7.9
authors: [Tebex_Limited, Omnivion]
website: http://buycraft.net
commands:
   buycraft:
      usage: /<command> <reload/forcecheck/secret/payments <ign>>
      description: Buycraft general purpose command.
   buysign:
      usage: /<command> <start/end/filter [Package ID]>
      description: Buycraft buysign configuration command.