name: Buycraft
main: net.buycraft.Plugin
version: 6.7.4
authors: [Tebex_Limited, Omnivion]
website: http://buycraft.net
commands:
   ec:
      usage: /<command>
   buycraft:
      usage: /<command> <reload/forcecheck/secret/payments <ign>>
   buysign:
      usage: /<command> <begin/end/filter [Package ID]>